### ISSUE TITLE
How to get the previous List price by using Ratecard API

### ISSUE THREAD

**Issue by jackting73** [Azure-Samples/billing-python-ratecard-api#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Hi,

Since the list price keep updating, how to get the historical list price by using the RateCard API because I didn't found the parameter can be used?

ex: the latest list price of Basic_A0 VM in westus is 500/mon in July, and the list price last year in July was 400/month. When I use the usage API to get the last year's consumed quantity, I can only have the latest list price which is equals to 500/mon, without the actual list price which can was 400/mon.

And parameter can be used to get the previous list price or workaround ? Thanks.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by toto90** [comment]
Hi, currently getting historical prices is not supported by the RateCard API. But we plan on supporting that feature in the next version of that API later this year. Thanks.
